### ISSUE TITLE
Just want to add version 11.0.0 version releases for the angular packages

### ISSUE THREAD

**Issue by Anelon** [esm-bundle/new-repo-instructions#11] opened 2021-02-11 15:03 UTC
### My username on npmjs.com

My username on npmjs.com is anelon

### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/angular__*@11.0.0

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

**Comment by joeldenning** [comment] 2021-02-12 00:10
Duplicate of https://github.com/esm-bundle/angular__core/issues/47

**Closed by joeldenning** 2021-02-12 00:10 UTC
